language: common-lisp

sudo: required

env:

install:
  # Install lisp support...
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - (cd rlgl-server; make coveralls)
