sudo: required

matrix:
  include:
    - language: common-lisp
      env:
        LISP=sbcl
      install:
        # Install lisp support...
        - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
        - apt list --installed
      script:
        - make coveralls
    - language: go
      before_install: cd rlgl
      before_deploy:
        - PLATFORMS=(darwin/amd64 linux/amd64 windows/amd64)
        - |
          for PLATFORM in ${PLATFORMS[@]"; do
            echo "Building $PLATFORM"
            GOOS=${PLATFORM%/*}
            GOARCH=${PLATFORM%*/}
            if [ "$GOOS" = "windows" ]; then
              build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -ldflags '-w -s'"
            else
              build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -ldflags '-d -w -s'"
            fi
            eval $build_cmd
            if [ $? ]; then
              echo Failed building rlrl cli for $PLATFORM" && return 1
            fi

            if [ "$GOOS" = "windows" ]; then
              zip rlgl-${GOOS}-${GOARCH}.zip rlgl
            else
              tar cvzf rlgl-${GOOS}-${GOARCH}.tgz rlgl
            fi
          done
          
      deploy:
        provider: releases
        api_key: $AUTH_TOKEN
        file:
          - "rlgl/rlgl-linux-amd64.tgz"
          - "rlgl/rlgl-darwin-amd64.tgz"
          - "rlgl/rlgl-windows-amd64.tgz"
        skip_cleanup: true
