sudo: required

services:
  - docker

env:
  LISP=sbcl
  REPO=moxielogic/rlgl-server

language: go
go:
- 1.9

before_install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh 
    | bash
  - (ls -l && cd rlgl && make depend && make build)
  - mv rlgl/build/* cli
  - docker build -f Dockerfile -t $REPO:latest .

#  - make coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag $REPO:latest $REPO:$COMMIT;
      docker push $REPO:latest;
      docker push $REPO:$COMMIT;
    fi
  - echo All done.
