sudo: required

matrix:
  include:
    - language: common-lisp
      env:
        LISP=sbcl
      install:
        # Install lisp support...
        - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
        - apt list --installed
      script:
        - make coveralls
    - language: go
      before_install: cd rlgl && make depend
      deploy:
        provider: releases
        api_key: $AUTH_TOKEN
        file:
          - "rlgl/build/rlgl-darwin-amd64.tgz"
          - "rlgl/build/rlgl-linux-amd64.tgz"
          - "rlgl/build/rlgl-linux-arm.tgz"
          - "rlgl/build/rlgl-windows-amd64.zip"
        skip_cleanup: true
