sudo: required

services:
  - docker

env:
  LISP=sbcl
  REPO=moxielogic/rlgl-server

language: go
go:
- 1.9

before_install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh 
    | bash
  - (cd rlgl && make depend && make build)
  - mv rlgl/build/* cli
  - pwd
  - ls -la
  - ls -l .git
  - echo ===================================================
  - echo $(git describe --tags --dirty=+)
  - echo "$(git describe --tags --dirty=+)"
  - echo `git describe --tags --dirty=+`
  - echo ===================================================
  - docker build -f Dockerfile --build-arg RLGL_VERSION="$(git describe --tags --dirty=+)" -t $REPO:latest .

#  - make coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker push $REPO:latest;
    fi
  - echo All done.
