sudo: required

git:
  depth: false

services:
  - docker

env:
  GO111MODULE=on
  LISP=sbcl
  REPO=quay.io/moxielogic/rlgl-server

language: go
go:
- 1.14

before_install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh
    |  bash
  - (cd rlgl && make build)
  - mv rlgl/build/* cli
  - docker build -f Dockerfile --build-arg RLGL_VERSION="$(git describe --tags --dirty=+)" -t $REPO:latest .
  - (cd keycloak-server-docker; docker build -f Dockerfile -t $REPO-keycloak:latest .)
#  - make coveralls

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
      docker tag $REPO:latest $REPO:$(git describe --tags --dirty=+);
      docker push $REPO:latest;
      docker push $REPO:$(git describe --tags --dirty=+);
      docker tag $REPO-keycloak:latest $REPO:$(git describe --tags --dirty=+);
      docker push $REPO-keycloak:latest;
      docker push $REPO-keycloak:$(git describe --tags --dirty=+);
    fi
  - echo All done.
