FROM quay.io/containerlisp/lisp-10-ubi8:f7790a3

COPY rlgl-server.asd /tmp

RUN sbcl --eval '(let* ((ds (with-open-file (stream "/tmp/rlgl-server.asd") \
                              (read stream)))                               \
                        (pos (position :DEPENDS-ON ds)))                    \
                   (dolist (p (nth (+ pos 1) ds))                           \
                     (ql:quickload p)))'
