language: lisp
sudo: required

env:
  matrix:
#    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
#    - LISP=sbcl32
    - LISP=ccl
#    - LISP=ccl32
#    - LISP=clisp
#    - LISP=clisp32
#    - LISP=cmucl
#    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;

script:
  - cl -e '(push *default-pathname-defaults* ql:*local-project-directories*)
           (ql:quickload :snooze)
           (ql:quickload :snooze-tests)
           (ql:quickload :fiasco)
           (defparameter *result* (fiasco:run-package-tests :packages
                                     (quote (:snooze-tests))))
           (unless *result* (uiop:quit 1))

           ;; Latest fiasco handles this much better, but the current verion in
           ;; quicklisp returns a list of test results (global contexts)
           ;;
           (when (and (consp *result*)
                      (notevery (function zerop)
                         (mapcar (function length)
                            (mapcar (function fiasco::failure-descriptions-of)
                               *result*))))
                 (uiop:quit 1))
            '