Name:           rlgl
Version:        2.0.2
Release:        1%{?dist}
Summary:        Git-centric policy management and enforcement tool

License:        AGPL-3.0-or-later
URL:            https://github.com/atgreen/red-light-green-light
Source0:        rlgl-%{version}.tar.gz

# Disable debug packages and stripping since this is a Lisp binary with a
# dumped image; stripping corrupts the embedded core.
%global debug_package %{nil}
%global _build_id_links none
%global __strip /bin/true
%global __brp_strip %{nil}
%global __brp_strip_comment_note %{nil}
%global __brp_strip_static_archive %{nil}

BuildRequires:  sbcl
BuildRequires:  gcc
BuildRequires:  make

# rlgl clones/pulls policy git repositories and runs the recog.d shell
# recognizers at runtime.
Requires:       git
Requires:       /bin/sh

%description
Red Light Green Light (rlgl) is a git-centric policy management and
enforcement tool for CI/CD pipelines.  It evaluates a test or scan report
against a policy stored in a git repository entirely on the local machine,
producing a self-contained HTML report and a GREEN (exit 0) or RED (exit 1)
result.

%prep
%autosetup -n rlgl-%{version}

%build
# Lisp dependencies are vendored in the source tarball (ocicl/).
make rlgl

%install
# Binary (self-contained: report recognition is built in, no data files)
install -D -m 0755 rlgl %{buildroot}%{_bindir}/rlgl

# SBOM (generated by the release workflow)
if [ -f rlgl-sbom.spdx.json ]; then
  install -D -m 0644 rlgl-sbom.spdx.json %{buildroot}%{_datadir}/sbom/rlgl-%{version}.spdx.json
fi

%files
%license COPYING
%doc README.md
%{_bindir}/rlgl
%{_datadir}/sbom/rlgl-%{version}.spdx.json

%changelog
* Thu Jun 18 2026 Anthony Green <green@moxielogic.com> - 2.0.2-1
- Use OS-native paths when invoking git so policy clone/blame work on Windows
* Thu Jun 18 2026 Anthony Green <green@moxielogic.com> - 2.0.1-1
- Built-in (pure-Lisp) report recognition; portable git invocation; no
  external recog.d/shell/grep dependency

* Thu Jun 18 2026 Anthony Green <green@moxielogic.com> - 2.0.0-1
- First release of rlgl as a standalone client-side tool (dropped the
  client-server architecture)
