name: OCI container image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Go 1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Build rlgl cli
      run: |
        (cd rlgl; make build)
        mv rlgl/build/* cli

    - name: Build the rlgl-server image
      run: |
        docker build . --file Dockerfile --build-arg RLGL_VERSION="$(git describe --tags --dirty=+)" --tag moxielogic/rlgl-server:$(git describe --tags --dirty=+)

    - name: Publish the image
      run: |
        docker login -u="${{ secrets.DOCKERHUB_USERNAME }}" -p="${{ secrets.DOCKERHUB_PASSWORD }}";
        docker tag moxielogic/rlgl-server:latest moxielogic/rlgl-server:$(git describe --tags --dirty=+);
        docker push moxielogic/rlgl-server:latest;
        docker push moxielogic/rlgl-server:$(git describe --tags --dirty=+);
